### ISSUE TITLE
AttributeError   启动服务后，登录进去的界面

### ISSUE THREAD

**Issue by fengasyou** [meanstrong/pydelo#7]
AttributeError
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'

Traceback (most recent call last)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1836, in **call**
return self.wsgi_app(environ, start_response)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1820, in wsgi_app
response = self.make_response(self.handle_exception(e))
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1403, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1817, in wsgi_app
response = self.full_dispatch_request()
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1477, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1381, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1475, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/lib/python2.6/site-packages/flask/app.py", line 1461, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/home/pydelo/web/controller/login.py", line 21, in decorator
if users.is_login(sign, apikey):
File "/home/pydelo/web/services/users.py", line 60, in is_login
if (session.expired-datetime.now()).total_seconds() > 0:
AttributeError: 'datetime.timedelta' object has no attribute 'total_seconds'

**Comment by fengasyou** [comment]
```
    if session is not None:
       # if (session.expired-datetime.now()).total_seconds() > 0:
           # return True
         return True
```

我直接跳过这段判断了

**Comment by meanstrong** [comment]
python2.6版本的timedelta没有total_seconds方法，我修改下。
