### ISSUE TITLE
ImportError: No module named Crypto.PublicKey

### ISSUE THREAD

**Issue by mintzhao** [meanstrong/pydelo#9]
iZ256wp3p78Z at ~/temp/pydelo ±(dev) ✗ ❯ python manage.py
Traceback (most recent call last):
  File "manage.py", line 4, in <module>
    from web import app
  File "/root/temp/pydelo/web/**init**.py", line 20, in <module>
    from .controller import api, webhooks, login, deploys, project, host, users
  File "/root/temp/pydelo/web/controller/api.py", line 20, in <module>
    from web.services.deploys import deploys
  File "/root/temp/pydelo/web/services/deploys.py", line 14, in <module>
    from web.utils.remoteshell import RemoteShell
  File "/root/temp/pydelo/web/utils/remoteshell.py", line 6, in <module>
    import paramiko
  File "/usr/local/lib/python2.7/dist-packages/paramiko/**init**.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 50, in <module>
    from paramiko.dsskey import DSSKey
  File "/usr/local/lib/python2.7/dist-packages/paramiko/dsskey.py", line 26, in <module>
    from Crypto.PublicKey import DSA
ImportError: No module named Crypto.PublicKey

**Comment by meanstrong** [comment]
Maybe your paramiko installed incorrect, you should install it by `pip install paramiko`, then you will see 
`
Successfully installed paramiko pycrypto ecdsa
Cleaning up...
`
otherwise, you need to install pycrypto and ecdsa manually，I rememberd pycrypto requires make、gcc，you need check it first.
